title: Documenting APIs
description: A guide for technical writers and engineers working with APIs
site_logo_file: learnapidoclogo-01.svg
language: english
sidebar: docapis
media: https://s3.us-west-1.wasabisys.com/idbwmedia.com/images/api
# Link to home
url: https://tubular-cactus-7895a0.netlify.app
baseurl: /learnapidoc

destination: learnapidoc
port: 4000
highlighter: rouge
exclude:
  - ebooks
  - pdf
format: web

plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate
# comment out jekyll-seo in order for algolia reindex to work
#  - jekyll-seo

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      topnav: topnav
  -
    scope:
      path: ""
      type: docs
    values:
      layout: default
      topnav: topnav
      progress: true
  -
    scope:
      path: "images"
    values:
      image: true

########## UI text ###############

uistring:
    tableofcontents: Table of Contents
    log_doc_issue: Log Doc Issue
    breadcrumb:
      home: Home
      documentation: Documentation
    expandall: Expand All
    collapseall: Collapse All
    title: Learn API Doc # Displays as site title on top nav bar and on site metadata
    description: A guide for technical writers and engineers learning how to document APIs  # Displays as site description meta
    github_edit_button_text: Edit on GitHub
    products: Products
    docindex_product: Product
    docindex_startpage: Starting page


####### Algolia configuration ###########
algolia:
  application_id: 7JEKBAXL1Y
  index_name: learnapidocs
  search_only_api_key: 268324bcfa734077d7983ed51a671760
  files_to_exclude:
    - ./toc.html
    - _docs/pdf_frontmatter/*
    - _docs/introduction_to_rest_apis/tocstart.html
    - _docs/introduction_to_rest_apis/tocstart_fulldetails.md
    - _docs/activities_pdf/*
    - _docs/slides/*
  nodes_to_index: 'p,.description'
####### jekyll seo tag configuration #######
title: Documenting APIs
tagline: A guide for technical writers and engineers learning how to document APIs
description: Online course about creating API documentation, mostly focusing on REST APIs but covering strategies for developer documentation in general. Includes sections on what an API is, API reference documentation, OpenAPI specification and Swagger, docs-as-code publishing and workflows, conceptual topics, tutorials, API documentation jobs, and more.
url: https://idratherbewriting.com
author:
  twitter: tomjohnson
twitter:
  username: tomjohnson
  card: summary

logo: https://s3.us-west-1.wasabisys.com/idbwmedia.com/images/idratherbewriting-site-logo.png

social:
  name: Tom Johnson
  links:
    - https://twitter.com/tomjohnson
    - https://www.facebook.com/tomidbw
    - https://www.linkedin.com/in/tomjoht/
    - https://github.com/tomjoht

facebook:
  app_id: 247143161970549
  publisher: 3968842976464

webmaster_verifications:
  google: i1qwK1LFgKEQHUtpm8o7OOOeK9i54NUQwKR4vXRqlFs
  bing: 352636FE6BAFC693A6938983FC6A227E

lang: en_US
