title: Simplifying Complexity
description: A series of essays on how to simplify complex concepts and information for the purposes of software documentation.
isbn: 000000000000000
cover_image: ebook_cover.png

sidebar: simplifying_complexity
