########## eBook tags (for docapis.opf) ###############
# see the docapis.opf file for more details
title: Documenting APIs
description: A guide for technical writers and engineers working with APIs
author: Tom Johnson
publisher: idratherbewriting.com
isbn: 000000000000000
subject: Technology & Engineering
cover_image: ebook_cover.png

language: english
media: images
format: kindle
sidebar: docapis

destination: _site
port: 5000
highlighter: rouge
exclude:
  - ebooks
  - pdf
  - slides
  - images/comics/
  - build_ebooks.sh
  - upload.sh
  - upload_outputs.sh
  - move.sh
  - reindex.sh
  - sitemap.xml
  - slides
  - thank-you-for-donating.html
  - contact.html
  - aws_cli_notes.txt
  - image_purge_output.sh
  - image_purge_source.sh
  - instructions.md
  - assets/files
  - assets/js

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: kindle
      topnav: topnav
  -
    scope:
      path: ""
      type: docs
    values:
      layout: kindle
      topnav: topnav
  -
    scope:
      path: images
    values:
      image: true
  -
    scope:
      path: images/comics/
    values:
      image: false
      published: false


########## UI text ###############


uistring:
    tableofcontents: Table of Contents
    log_doc_issue: Log Doc Issue
    breadcrumb:
      home: Home
      documentation: Documentation
    expandall: Expand All
    collapseall: Collapse All
    title: Learn API Doc # Displays as site title on top nav bar and on site metadata
    description: A guide for technical writers and engineers learning how to document APIs  # Displays as site description meta
    github_edit_button_text: Edit on GitHub
    products: Products
    docindex_product: Product
    docindex_startpage: Starting page
